/**
 * GPX export utility.
 * Converts BRouter GeoJSON routes to GPX format and triggers browser download.
 */

import { formatTime, sanitizeFilename } from '../utils.js';

/**
 * Export a single route as a GPX file.
 *
 * @param {object} result - Route result from stationFinder
 */
export function exportRouteAsGPX(result) {
  const filename = sanitizeFilename(`${result.lines.map(l => l.id).join('_')} - ${result.station.name} to home.gpx`);
  const gpx = buildGPX([result]);
  downloadFile(gpx, filename, 'application/gpx+xml');
}

/**
 * Export all routes as a single GPX file with multiple tracks.
 *
 * @param {Array} results - Array of route results
 */
export function exportAllRoutesAsGPX(results) {
  const gpx = buildGPX(results);
  const date = new Date().toISOString().slice(0, 10);
  downloadFile(gpx, `train-bike-berlin-${date}.gpx`, 'application/gpx+xml');
}

// --- Internal ---

function buildGPX(results) {
  const now = new Date().toISOString();
  const tracks = results.map(r => routeToTrack(r)).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Train+Bike Berlin Planner"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>Train+Bike Berlin Routes</name>
    <desc>Bike routes from train stations back to Berlin, generated by Train+Bike Planner</desc>
    <time>${now}</time>
  </metadata>
${tracks}
</gpx>`;
}

function routeToTrack(result) {
  const name = `${result.lines.map(l => l.id).join(' / ')}: ${result.station.name} → Home`;
  const desc = `${result.bikeDistanceKm} km | ↑${result.elevationGainM} m | ~${formatTime(result.estimatedTimeMin)}`;
  const coords = extractCoords(result.bikeRoute);
  const trkpts = coords.map(([lon, lat, ele]) => {
    const eleTag = ele != null ? `\n          <ele>${Math.round(ele)}</ele>` : '';
    return `        <trkpt lat="${lat.toFixed(6)}" lon="${lon.toFixed(6)}">${eleTag}\n        </trkpt>`;
  }).join('\n');

  return `  <trk>
    <name>${escapeXml(name)}</name>
    <desc>${escapeXml(desc)}</desc>
    <type>cycling</type>
    <trkseg>
${trkpts}
    </trkseg>
  </trk>`;
}

function extractCoords(geojson) {
  return geojson?.features?.[0]?.geometry?.coordinates ?? [];
}

function escapeXml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
